# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master
    

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy PP.SqlClr.DirectoryServices binaries'
  inputs:
    SourceFolder: 'PP.SqlClr.DirectoryServices\bin\$(BuildConfiguration)'
    Contents: '*.dll'
    TargetFolder: '$(build.artifactstagingdirectory)\PP.SqlClr.DirectoryServices'
    CleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy PP.SqlClr.DirectoryServicesAccounts binaries'
  inputs:
    SourceFolder: 'PP.SqlClr.DirectoryServicesAccounts\bin\$(BuildConfiguration)'
    Contents: '*.dll'
    TargetFolder: '$(build.artifactstagingdirectory)\PP.SqlClr.DirectoryServicesAccounts'
    CleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy PP.SqlClr.External binaries'
  inputs:
    SourceFolder: 'PP.SqlClr.External\bin\$(BuildConfiguration)'
    Contents: '*.dll'
    TargetFolder: '$(build.artifactstagingdirectory)\PP.SqlClr.External'
    CleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy PP.SqlClr.Safe binaries'
  inputs:
    SourceFolder: 'PP.SqlClr.Safe\bin\$(BuildConfiguration)'
    Contents: '*.dll'
    TargetFolder: '$(build.artifactstagingdirectory)\PP.SqlClr.Safe'
    CleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy PP.SqlClr.SharePoint binaries'
  inputs:
    SourceFolder: 'PP.SqlClr.SharePoint\bin\$(BuildConfiguration)'
    Contents: '*.dll'
    TargetFolder: '$(build.artifactstagingdirectory)\PP.SqlClr.SharePoint'
    CleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy PP.SqlClr.Types binaries'
  inputs:
    SourceFolder: 'PP.SqlClr.Types\bin\$(BuildConfiguration)'
    Contents: '*.dll'
    TargetFolder: '$(build.artifactstagingdirectory)\PP.SqlClr.Types'
    CleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy PP.SqlClr.Unsafe binaries'
  inputs:
    SourceFolder: 'PP.SqlClr.Unsafe\bin\$(BuildConfiguration)'
    Contents: '*.dll'
    TargetFolder: '$(build.artifactstagingdirectory)\PP.SqlClr.Unsafe'
    CleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy SQL Scripts'
  inputs:
    Contents: '**/*.sql'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'PPSqlClr'
    publishLocation: 'Container'